## Enable blank issues as a temporary workaround until Issue Templates are
## working correctly on all browsers and platforms.
blank_issues_enabled: true
contact_links:
  - name: Qubes Forum
    url: https://forum.qubes-os.org/
    about: Get help, ask questions, and discuss Qubes
  - name: qubes-users mailing list
    url: https://www.qubes-os.org/support/#qubes-users
    about: Get help, ask questions, and discuss Qubes
  - name: qubes-devel mailing list
    url: https://www.qubes-os.org/support/#qubes-devel
    about: Technical discussion for developers and code contributors
  - name: qubes-project mailing list
    url: https://www.qubes-os.org/support/#qubes-project
    about: Non-technical discussion and coordination of project matters
  - name: qubes-translation mailing list
    url: https://www.qubes-os.org/support/#qubes-translation
    about: All localization and translation topics
